check_is_login_confirm_message: Please login first
check_is_login_confirm_label: OK
check_is_login_cancel_label: Cancel
check_is_login_redirect: ''

custom_header_items: true
header_items:
  type: list
  default: ''
subheader_items:
  type: list
  default: ''
third_level_items:
  type: list
  # default: 1-1,Baidu;https://baidu.com
  default: ''

remove_home_page_search_button: false

close_custom_badges_effect: false

deployment_env:
  default: production
  type: enum
  choices:
    - production
    - development

community_ui_ts:
  default: 0
  type: integer
